### ISSUE TITLE
noisy prompt for remove entries every time 

### ISSUE THREAD

**Issue by jackywu** [nvim-telescope/telescope-frecency.nvim#104]
with configuration 
```
➜  custom git:(main) ✗ cat configs/telescope.lua
local opts = {
  extensions = {
      frecency = {
        show_scores = true,
        show_unindexed = true,
        db_safe_mode = false,
        auto_validate = false,
        workspaces = {
        }
      }
    },
}
```
I use `nvim a.py` , the plugin always tell me confrm if remove entries twice.
![Xnip2023-07-06_17-39-19](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/587955/73d26162-a387-4bfb-955d-efd462037e13)
![Xnip2023-07-06_17-39-25](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/587955/c95ec501-e61a-479c-9bb3-8ae76698070e)

**Comment by lixin-sxty** [comment]
I got the same problem

**Comment by delphinus** [comment]
Does this still happen? Probably, it has been fixed. If you see this again, open again.

**Comment by cehoffman** [comment]
I see this still and have upgraded.
