### ISSUE TITLE
Frecency shows deleted/renamed entries

### ISSUE THREAD

**Issue by xuanhung1509** [nvim-telescope/telescope-frecency.nvim#105]
Suppose I have a file named `test.js` located at `nvim/lua/test.js`. Afterwards, I rename the file to `test.lua`. Frecency now shows both `test.js` and `test.lua`.

```bash
.
├── init.lua
├── lazy-lock.json
├── LICENSE
└── lua
    ├── core
    │   ├── ...
    ├── custom
    │   ├── ...
    ├── plugins
    │   ├── ...
    └── test.lua
```
![image](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/89293664/9ccf0dd3-4761-4833-b4ee-a64cdcbc9b48)

The same happens if I create a file and then delete it, frecency still shows the deleted file.

I'm using Nvchad if that matters.

**Comment by delphinus** [comment]
This is a spec in the current logic, at least. 

* It does not remove deleted entries until it reaches the threshold: https://github.com/nvim-telescope/telescope-frecency.nvim/blob/62d3381a32ae541233b03a129ece0aeced30ad5e/lua/frecency/db.lua#L177-L181
* It caches the result from DB until you select another workspace: https://github.com/nvim-telescope/telescope-frecency.nvim/blob/62d3381a32ae541233b03a129ece0aeced30ad5e/lua/frecency/picker.lua#L101-L103

**Comment by delphinus** [comment]
After refactoring in #100, it does not cache results and fetch them from DB every time.

Deleted files are removed when `auto_validate` options is `true` (default value), but it does not work if deleted files are less than `db_validate_threshold` (default: `10`). If you wish even one entries should be removed when it is deleted, set `db_validate_threshold = 1`.
