### ISSUE TITLE
Calling plenary.scandir is slow

### ISSUE THREAD

**Issue by jonashaag** [nvim-telescope/telescope-frecency.nvim#106]
In the default config, opening frecency is much slower than Telescope's built-in `find_files` because `plenary.scandir` is really slow. I think it doesn't use ripgrep/fd.

**Comment by delphinus** [comment]
I'm refactoring the whole source in #100, and planning to use `vim.fs.dir` instead of `plenary.scandir` not to block Neovim. It seems to work nicely in my env.

**Comment by delphinus** [comment]
I merged #100. Now it does not block your input even on a folder containing huge amount of files.
