### ISSUE TITLE
don't know how to describe

### ISSUE THREAD

**Issue by ikkihou** [nvim-telescope/telescope-frecency.nvim#112]
- OS : MacOs
- term : iTerm2

I just updated the plugin and got the error below, and I have no idea how to debug it. Has anyone got this kind of error either?

<img width="1800" alt="Screenshot 2023-08-07 at 00 16 49" src="https://github.com/nvim-telescope/telescope-frecency.nvim/assets/51254965/0d46c85f-a240-49ae-bcc1-b306d0c28e82">

my telescope setup:
<img width="712" alt="Screenshot 2023-08-07 at 00 22 22" src="https://github.com/nvim-telescope/telescope-frecency.nvim/assets/51254965/3d02d522-78dc-4b0b-a7c9-59e1bdf5c670">
<img width="1800" alt="Screenshot 2023-08-07 at 00 23 33" src="https://github.com/nvim-telescope/telescope-frecency.nvim/assets/51254965/6df3636c-f7a2-4ae8-8a9f-997d691963be">

**Comment by delphinus** [comment]
Sorry, this is a bug. Already fixed.
