### ISSUE TITLE
Feature Request: Frecency + find_files

### ISSUE THREAD

**Issue by taylon** [nvim-telescope/telescope-frecency.nvim#13]
Currently when we invoke frecency it only lists files "frecently" opened. Which means that we need to have two different keybindings for finding files, one for `frecency` and another one for `list_files` and we need to make that choice everytime we want to open a file.

It would be great to have only one keybind to navigate through files but have them sorted by frecency.
Basically, list the frecency files, but also show the results from list_files.

If I'm not mistaken (never actually used it much) VSCode does exactly that with their file finder, except that it is restricted by the current project I think, which is worse than the current frecency approach which can navigate through any file recently opened which I think is much more powerful, specially if combined with something that changes the current directory to the project root of the selected file

**Comment by Conni2461** [comment]
@sunjon currently provides this `tag` feature with an `show_unindexed` option which should be true pre default. See README.

So what i am doing is. Open `frecency` type `:LSP:` (has tab completion) which currently requires `builtin-lsp` but it will get the current workspace and all unindexed files. So basically a `find_files`. It still sorts with the calculated value tho. But its pretty useful. And it will remember the tag. So the next time opening `:LSP:` is already applied.

You can also define your own tags. So if i wanna look at a different project i can just write/complete that tag and get all files.

**Comment by sunjon** [comment]
Like Connie said, I think this functionality already exists.
I can try make the readme/gifs better if all the features aren't clear enough.
Let me know if you don't get the `:foo<tab>` filtering working.

**Comment by aleksanderEE** [comment]
@sunjon that would be useful!

**Comment by aleksandersumowski** [comment]
@sunjon that would be useful!
