### ISSUE TITLE
Idea: inc frecency by how often buffer used

### ISSUE THREAD

**Issue by quolpr** [nvim-telescope/telescope-frecency.nvim#131]
Hey! Nice plugin, but I really miss one feature. Telescope has a nice built-in feature that shows the most recent used buffer — https://github.com/nvim-telescope/telescope.nvim/issues/791 . To use it, you need to call: `require("telescope.builtin").buffers { sort_mru = true, ignore_current_buffer = true }`. 

Would it be possible to adopt the most recent used buffer to frecency?

**Comment by delphinus** [comment]
`:Telescope frecency` sorts candidates by their “frecency” scores. If we sort by another logic (`sort_mru`) additionally, the candidates will be sorted that is not relevant to “frecency”. It is not the aim of this plugin.
