### ISSUE TITLE
Feature Request: a built in workspace :cwd:

### ISSUE THREAD

**Issue by TC72** [nvim-telescope/telescope-frecency.nvim#14]
A way to specify we only want files below the current working directory.
Making a built in :cwd: similar to the builtin :LSP: would work.

I would prefer to just pass in the directory I want it to filter on using an opt{}, but after looking through the codebase using a workspace looks like the simpler solution.

**Comment by teto** [comment]
fully agree. I wish I wouldn't have to add a workspace for every folder I visit. I personnally would use :cwd: as a default too. Like fzf Files but sorted by frecency

**Comment by teto** [comment]
regardless of an hypothetical :cwd: , would it be possible to default the input to :lsp: . My workflow is one neovim isntance per project so never need to see other projects from my current instance.

**Comment by sunjon** [comment]
> regardless of an hypothetical :cwd: , would it be possible to default the input to :lsp: . My workflow is one neovim isntance per project so never need to see other projects from my current instance. 

You can pass  query text to the finder in the config you pass to telescope. Does setting that to `:lsp:` do what you want?

**Comment by sunjon** [comment]
added in https://github.com/nvim-telescope/telescope-frecency.nvim/pull/18
Let me know if it doesn't work as you expected.

**Comment by teto** [comment]
thanks it works for me ! `Telescope frecency`  displays the CWD before the filepath which seems unnnecessary but apart from that great.

**Comment by 3nuc** [comment]
If anybody's launching `:Telescope frecency` then writing `:cwd:` inside and it's not filtering -- try `:CWD:` (same with :lsp: and :LSP:)
