### ISSUE TITLE
Is it possible to remove an entry from telescope-frecency?

### ISSUE THREAD

**Issue by vinoff** [nvim-telescope/telescope-frecency.nvim#151]
Is it possible to remove an entry from telescope-frecency?

Say I worked extensively on a given file but wish to no longer work on it. I want it removed from telescope-frecency. Is there a way to delete its entry from the DB (or change its ranking), without having to add it to the ignore patterns? Or is adding it to the ignore the only way?

**Comment by delphinus** [comment]
There is no such feature. But it is reasonable that it can do. I will implement it.

```vim
" delete from DB with supplied full path
:FrecencyDelete ~/path/to/file
" path can be expand()
:FrecencyDelete %  " ← This means the file in the current buffer
```

**Comment by vinoff** [comment]
@delphinus , do you plan on merging this to master anytime soon?

**Comment by delphinus** [comment]
Sorry for late. I'm writing tests for it, so wait a minute pls 🙏🏻

**Comment by delphinus** [comment]
Again sorry for late. At last I merged the PR.

And I changed syntax a little.

```vim
" delete from DB with supplied full path
:FrecencyDelete ~/path/to/file
" path can be expand()
:FrecencyDelete %:p  " ← This means the file in the current buffer
" delete the file in the current buffer
:FrecencyDelete
```

You can delete the file from DB with opening the file & type `:FrecencyDelete` only.
