### ISSUE TITLE
How to read file_frecency.bin using external tools?

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [nvim-telescope/telescope-frecency.nvim#157]
Title. I'd like to access the list of files outside of nvim environment.

**Comment by delphinus** [comment]
@limaceous-bushwhacker 

This file contains Lua bytecode, so it is difficult to read it from outside of Neovim.

One suggestion is that we can export a function to load `file_frecency.bin` to output JSON. Such as,

```bash
$ nvim +FrecencyExportJSON +q
{"foo":{"bar":[...]}}
```

You need such command? What is your usecase?
