### ISSUE TITLE
Fuzzy matching is worse than normal telescope

### ISSUE THREAD

**Issue by sahinakkaya** [nvim-telescope/telescope-frecency.nvim#163]
~I don't know if this is expected behaviour~ (yes, it was. `:FrecencyValidate!` to fix) ~but when I run this extension, it shows me deleted files~. And also the sorting seems to not working. See the screenshot attached:

 
![20240105_14h10m59s_grim](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/32161460/e6f70565-7f31-46b6-9952-e348d993efcb)

~As you can see from the right side of the terminal window, there is only 4 files in the current working directory. `style/` directory is deleted. But it still shows up in `Telescope frecency workspace=CWD` window.~ 

Also, `config.js` is not first item on the list even though I almost typed the whole file name. 

Edit: I was able to fix showing deleted files issue by using `:FrecencyValidate!`. But it is still sorting files awkwardly.

**Comment by delphinus** [comment]
You cannot use fuzzy-match for this picker. When you use it, telescope sorts the results again without frecency's scores ;( See https://github.com/nvim-telescope/telescope-frecency.nvim/pull/1#issuecomment-764586539

In default, this picker always uses `sorters.get_substr_matcher()` (see [here](https://github.com/nvim-telescope/telescope-frecency.nvim/blob/9c18474d0a4b82435ce141c2a21d9bd7b9189272/lua/frecency/picker.lua#L111)). How do you use fuzzy-match with this picker? I want to see your setup (init.lua).

**Comment by sahinakkaya** [comment]
> How do you use fuzzy-match with this picker? I want to see your setup (init.lua).

I think you misunderstood  me. I couldn't use fuzzy match and that was my request in the issue. But I got your point now. If I, sort understand correctly, sorting the result is handed of to telescope and you can't use a custom sorter for this plugin. If this is the case, there is nothing can be done here to fix it.

**Comment by sahinakkaya** [comment]
And I also understand why you got me wrong. I misused the term "fuzzy matching" in the title while meaning telescope search results. Since telescope runs fuzzy-matcher on most of its operations, I called it normal telescope :D

**Comment by delphinus** [comment]
Ah I see. I listened to you and thought it is good if such sorter, that uses fuzzy-matching and frecency scores, exists. I issued that to #165. I try it later.
