### ISSUE TITLE
`remove n entries from database?` message displays on a floating window and cannot focus on it

### ISSUE THREAD

**Issue by yoshiyoshiharu** [nvim-telescope/telescope-frecency.nvim#167]
When I start nvim, the message `remove n entries from database?` appears on a floating window, and I cannot focus on it.
Therefore, I cannot remove entries.
Could anyone help me?

<img width="1440" alt="image" src="https://github.com/nvim-telescope/telescope-frecency.nvim/assets/54305137/b2a2a7b3-81f8-4b32-bc0c-4ddd729322a1">

**Comment by delphinus** [comment]
#162 did a change for this. You can set `db_safe_mode = off` in `setup {}` to disable such confirmation dialog always.

**Comment by ForsakenHarmony** [comment]
This doesn't really fix the issue of the floating window you can't focus?

**Comment by delphinus** [comment]
You see the dialog even if you set `db_safe_mode = false` ? Really?
