### ISSUE TITLE
setting to avoid the prompt to remove outdated entries

### ISSUE THREAD

**Issue by teto** [nvim-telescope/telescope-frecency.nvim#17]
I get prompted daily and it's annoying, especially as my database is certainly very small and thus it shouldn't be an issue (or some inexisting files may appear ?). Triggered when I switch branch etc. 

Not sure what the policy should be:
- prompt no more than once a week
- prompt starting from a certain size of the db
- let the user cleanup the db when advised by checkhealth with one of the aforementioned issues
etc

**Comment by sunjon** [comment]
Let me know if https://github.com/nvim-telescope/telescope-frecency.nvim/pull/20 solves the issue for you.

**Comment by teto** [comment]
> It will remove the prompt and confirmation will be assumed to be true.

I would prefer to keep the frecency for these files since in my case they just temporarily disappear from the drive. I would rather run the cleanup function manually.

**Comment by sunjon** [comment]
fixed in https://github.com/nvim-telescope/telescope-frecency.nvim/pull/20 . Sorry for the delay!
