### ISSUE TITLE
Hide active buffer from list

### ISSUE THREAD

**Issue by TylerBarnes** [nvim-telescope/telescope-frecency.nvim#175]
Is it possible to hide the buffer the cursor was on just before the telescope picker was opened?
This would make it easier to rapidly switch between highly frecent buffers. I looked through the options but didn't see anything that might be used to achieve this.
I think there isn't a case where I would want to open the frecency picker and go back to the file I was already on before I opened it.

**Comment by delphinus** [comment]
Nice idea. I will add `hide_current_buffer` option.

**Comment by delphinus** [comment]
I added the option. Check it.
