### ISSUE TITLE
Bind extension to function?

### ISSUE THREAD

**Issue by phortonssf** [nvim-telescope/telescope-frecency.nvim#185]
As the title says, I am trying to bind frecency as a function to pass in dynamic config.   The default way documented works but i can't seem to invoke this extension as I am  able to invoke other telescope extensions. I instead get the error unable to find frecency. 

`
 vim.keymap.set("n", "<leader>fr", function()
     require("telescope").extensions.frecency({})
end)

`

**Comment by phortonssf** [comment]
[Solved] Of course I find a soluton right after posting.
`
vim.keymap.set("n", "fr", function()
require("telescope").extensions.frecency.frecency({})
end)

`

**Comment by delphinus** [comment]
Yes, it lacks info about such way. I added a note to launch frecency via Lua function.
