### ISSUE TITLE
[Feature request] ignore_pattern accept function

### ISSUE THREAD

**Issue by Song-Tianxiang** [nvim-telescope/telescope-frecency.nvim#187]
I want to ignore files that have set `nobuflisted`. How can I achieve this? Can we make ignore_pattern accept a function and give user more control.

**Comment by delphinus** [comment]
Nice idea. We can ignore any file not to register into DB as we like. I will implement it.

**Comment by delphinus** [comment]
I added `ignore_register` option to achieve this. For example, you can ignore to register files that is `'nobuflisted'`.

```lua
telescope.setup {
  extensions = {
    frecency = {
      ignore_register = function(bufnr)
        return not vim.bo[bufnr].buflisted
      end,
    }
  },
}
