### ISSUE TITLE
[BUG] TelescopeBufferLoaded only highlight buffers loaded before Frecency initialized

### ISSUE THREAD

**Issue by zhengpd** [nvim-telescope/telescope-frecency.nvim#201]
Only buffers loaded before Frecency initialized are highlighted in telescope prompt. I guess it's because Frecency use singleton and `EntryMaker.new` is only called once on initialization, which sets the loaded buffers table.

**Comment by delphinus** [comment]
I see. I agree with your fix. Thank you.
