### ISSUE TITLE
Deleted files still show up in search

### ISSUE THREAD

**Issue by Tired-Fox** [nvim-telescope/telescope-frecency.nvim#207]
Files that have been deleted from the file system still show up in the results. After running `FrecencyValidate` the files are still there. I have to manually delete them from the DB with `FrecencyDelete`

![WindowsTerminal_4gQaqoyvQb](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/94603332/25141963-45bd-43de-bf5a-50e2de9c4a5f)

**Comment by delphinus** [comment]
You mean, after you renamed `temp\Test.py` into `temp\test.py` and did `:FrecencyValidate`, it still shows both files in candidates, right?

Strange. I will look into this further.

**Comment by Tired-Fox** [comment]
That is correct. Restarting nvim doesn't fix anything either. Have to run `:FrecencyDelete <full path to file>` to remove it

**Comment by delphinus** [comment]
I found the cause. The decision to distinguish the file's existence depends on `vim.uv.fs_stat(filename).type == "file"`. Even if the filename is `foo.lua`, `fs_stat("Foo.lua")` returns stat for `foo.lua` implicitly. Capital or lower cases does not make sense.

I think this is a limitation of this plugin because `vim.uv` has the same limitation.

**Comment by delphinus** [comment]
I'm thinking about an implementation to detect accurate filenames for removing entries.

```lua
local function path_exist(path)
  local parent = vim.fs.dirname(path)
  local dir = uv.fs_opendir(parent)
  local entries = uv.fs_readdir(dir)
  for _, entry in ipairs(entries) do
    if entry.type == "file" and vim.fs.joinpath(parent, entry.name) == path then
      return true
    end
  end
  return false
end
```

If `/path/to/Foo.lua` does not exist, but `/path/to/foo.lua` does, `path_exist "/path/to/Foo.lua"` returns `false`, although  `uv.fs_stat "/path/to/Foo.lua"` returns a truthy value.

**Comment by delphinus** [comment]
I stopped to implement this logic above because a significant problem occurs -- symlink. It is too difficult to manage targets if they are symlinks.

I also found one more problem already has been occurring: #230. We should think about more robust logic.

**Comment by delphinus** [comment]
Now we use realpath to detect filenames. For this case, `:FrecencyValidate` detects the file definitely exists and removes the entry from DB if it does not exist.
