### ISSUE TITLE
`show_unindexed` showing ignored files

### ISSUE THREAD

**Issue by joey-slingshot** [nvim-telescope/telescope-frecency.nvim#211]
I'm not sure if this is intended behavior, but when I have `show_unindexed` set to `true` (I do this for git repos I haven't used with nvim before so I can search for files that haven't been index), if I open the frecency window, I still see files inside the `.git` directory although I've tried the `ignore_patterns` settings at both the root and extension levels.

My telescope config looks like this:

```lua
      require('telescope').setup {
        defaults = {
          file_ignore_patterns = { '*.git' },
        },
        extensions = {
          frecency = {
            ignore_patterns = { '*.git' },
            show_unindexed = true,
            db_safe_mode = false,
            auto_validate = false,
            default_workspace = 'CWD',
          },
        },
      }
```

**Comment by delphinus** [comment]
Hmm, I can't reproduce.

1. I wrote a minimal `init.lua` to `~/.config/nvim-frecency/init.lua` like below,

   <details><summary>code: <code>~/.config/nvim-frecency/init.lua</code></summary>

   ```lua
   local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
   if not vim.loop.fs_stat(lazypath) then
     vim.fn.system {
       "git",
       "clone",
       "--filter=blob:none",
       "https://github.com/folke/lazy.nvim.git",
       "--branch=stable", -- latest stable release
       lazypath,
     }
   end
   vim.opt.rtp:prepend(lazypath)

   require("lazy").setup {
     {
       "nvim-telescope/telescope.nvim",
       dependencies = {
         { "nvim-lua/plenary.nvim" },
         { "nvim-telescope/telescope-frecency.nvim" },
       },
       config = function()
         require("telescope").setup {
           defaults = {
             file_ignore_patterns = { "*.git" },
           },
           extensions = {
             frecency = {
               ignore_patterns = { "*.git" },
               show_unindexed = true,
               db_safe_mode = false,
               auto_validate = false,
               default_workspace = "CWD",
             },
           },
         }
       end,
     },
   }
   ```
   </details>

2. Run `env NVIM_APPNAME=nvim-frecency nvim`
3. Run `:Telescope frecency`
4. But I cannot see entries below `.git` dir.

Two points I want to know:

1. Do you have `rg` or `fd` in your env?
2. If you set `workspace_scan_cmd = "LUA"` and try it, do you see `*.git` entries?

**Comment by joey-slingshot** [comment]
1a. `fd` in my env is just my alias for `find . -type d -name`
1b. I do have `rg` (ripgrep).
2. Setting `workspace_scan_cmd = "LUA"` fixed my issue. Thanks!

**Comment by jsvensson** [comment]
Just a brief +1 on this issue -- I'm using LazyVim as a base for my setup and at some point this started happening. Setting the `workspace_scan_cmd` worked for me too.

**Comment by rizkyilhampra** [comment]
+1 for this issue. set `workspace_scan_cmd = "LUA"` is worked, but it has new issue, nested `.gitignore` files are not respected

**Comment by matthewgrossman** [comment]
`workspace_scan_cmd = "LUA"` locally worked for me as well.

This only started happening recently for me, my guess is due to this PR: https://github.com/nvim-telescope/telescope-frecency.nvim/commit/328452afcc29187732575842c19172f4d4ed749d

The newly added `fd` command doesn't ignore `.git/` files it seems:
```
» fd -Htf | head -5
.git/COMMIT_EDITMSG
.git/FETCH_HEAD
.git/HEAD
.git/ORIG_HEAD
.git/config
```
Assuming the `-H` was intentional, I think the easy fix here is to `--exclude .git` (and this also matches what is done for `rg` anyways). Here's a quick PR if that looks good: https://github.com/nvim-telescope/telescope-frecency.nvim/pull/221/files

**Comment by delphinus** [comment]
Hmm..., I cannot reproduce it. For example, I have created a new git repo, and `fd -Htf` in it. Then it does not show any `.git/*` entries.

```bash
~ ❯❯❯ mkdir /tmp/foo
~ ❯❯❯ cd /tmp/foo
/t/foo ❯❯❯ git init
Initialized empty Git repository in /private/tmp/foo/.git/
/t/foo () ❯❯❯ fd -Htf
/t/foo () ❯❯❯ ls .git
HEAD         config       description  hooks/       info/        objects/     refs/
/t/foo () ❯❯❯
```

But with `-I` in addition to `-H`, it shows `.git/*` entries.

```bash
/t/foo () ❯❯❯ fd -I
/t/foo () ❯❯❯ fd -IH
.git/
.git/HEAD
.git/config
.git/description
.git/hooks/

……

/t/foo () ❯❯❯
```

I'm using fd v9.0.0. What version do you use? @matthewgrossman 

```bash
/t/foo () ❯❯❯ fd --version
fd 9.0.0
/t/foo () ❯❯❯ 
```

**Comment by matthewgrossman** [comment]
Ah yes, I'm on a newer version it seems, `10.1.0`:

```
 ~/src/telescope-frecency.nvim  master  » fd --version     
fd 10.1.0
 ~/src/telescope-frecency.nvim  master  » fd -Htf | head -5
.git/FETCH_HEAD
.git/HEAD
.git/config
.git/description
.git/hooks/applypatch-msg.sample
```

**Comment by matthewgrossman** [comment]
This appears to be a breaking change of `fd` in version `10.0.0` :-/ https://github.com/sharkdp/fd/releases/tag/v10.0.0

**Comment by delphinus** [comment]
Finally I noticed I have not did `brew upgrade` recent months ;)

I did `brew upgrade fd`, and installed v10.1.0, then reproduced this!

```bash
/t/foo () ❯❯❯ fd -Htf
.git/HEAD
.git/config
.git/description
.git/hooks/applypatch-msg.sample
.git/hooks/commit-msg.sample

……

/t/foo () ❯❯❯ 
```

It seems v0.10 did breaking changes 🤔

**Comment by delphinus** [comment]
It says the same thing.

https://github.com/sharkdp/fd/releases/tag/v10.0.0

> Breaking: No longer automatically ignore .git when using --hidden with vcs ignore enabled.

I will check #221.

**Comment by delphinus** [comment]
Thank you @matthewgrossman. This issue has been fixed. Check it all.
