### ISSUE TITLE
[Feature] Add an option to enable or disable debug logging

### ISSUE THREAD

**Issue by pidgeon777** [nvim-telescope/telescope-frecency.nvim#212]
This plugin utilizes `plenary.nvim` for debugging, specifically the `plenary.log` module.

The issue arises because this module is also employed by other plugins. The current implementation of `telescope-frecency.nvim` does not provide an option to disable this automatic debug logging. Consequently, its debug entries are mixed with those of other plugins.

I propose the addition of a configuration option to disable debug logging. This would allow users to enable it only when necessary. Alternatively, and perhaps more effectively, a second step could be to provide a way to create a "frecency only" debug file.

**Comment by delphinus** [comment]
Fixed. If you feel still annoying, reopen this 👍🏻
