### ISSUE TITLE
How can I get this to work and look like find_files?

### ISSUE THREAD

**Issue by Kurren123** [nvim-telescope/telescope-frecency.nvim#218]
`find_files` is great because it:

- ignores the .git folder
- only searches the current directory without the need for tags
- displays all paths relative to the current directory

![image](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/3525980/8f2647c5-296b-47ec-aaa8-ca92e9a9ea01)

Is it possible to configure `telescope-frecency` to just be a strictly better version of `find_files`? The default installation searches all directories in the system. If I add `workspace = CWD` I get:

![image](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/3525980/d97379bb-ddb3-485c-9c7f-9bc72a788313)

Which has the following disadvantages:

1. File paths are not shown relative to the current folder
2. The workspace folder name is repeated for every entry, which takes up space and could be a problem if the folder name is large.
3. It doesn't ignore the .git folder

I've looked through the help manual but can't find any simple config options to remedy the above. I can of course write a custom function for `path_display` to make it relative to the CWD, but seeing as `find_files` already has this there must be something existing I can use? I an also add my own exclusion list for number 3 above but again I'm wondering if I can just reuse the one from `find_files`?

Many thanks

**Comment by delphinus** [comment]
It seems this occurs because it is on Windows. Later I will try to reproduce after preparing Windows env.

**Comment by Kurren123** [comment]
Thanks. Is there any way I can help?

**Comment by delphinus** [comment]
I tested the latest telescope & telescope-frecency on Neovim 0.9.5, and could not reproduce this.

1. I wrote this into `C:\Users\foo\AppData\Local\nvim-frecency\init.lua`.

   <details><summary>minimal init.lua</summary>

   ```lua
   local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
   if not (vim.uv or vim.loop).fs_stat(lazypath) then
     vim.fn.system {
       "git",
       "clone",
       "--filter=blob:none",
       "https://github.com/folke/lazy.nvim.git",
       "--branch=stable", -- latest stable release
       lazypath,
     }
   end
   vim.opt.rtp:prepend(lazypath)

   require("lazy").setup({
     {
       "nvim-telescope/telescope.nvim",
       dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope-frecency.nvim" },
       config = function()
         local telescope = require "telescope"
         telescope.setup {}
         telescope.load_extension "frecency"
         local builtin = require "telescope.builtin"
         vim.keymap.set("n", "<C-p>", builtin.find_files)
         vim.keymap.set("n", "<C-f>", function()
           telescope.extensions.frecency.frecency { workspace = "CWD" }
         end)
       end,
     },
   })
   ```
   </details>

2. And launch Neovim with `$NVIM_APPNAME`.

   ```
   set NVIM_APPNAME=nvim-frecency
   cd C:\Users\foo\AppData\Local
   nvim
   ```
3. Type `<C-f>` to run telescope-frecency.

   <img width="653" alt="スクリーンショット 2024-07-13 22 50 25" src="https://github.com/user-attachments/assets/653310bb-3482-42c6-81d7-d55975caf64a">

@Kurren123 Are you using the latest telescope-frecency? And what version of Neovim do you use?

**Comment by delphinus** [comment]
@Kurren123 Report a reproducible process for this if you still see the problem. Feel free to reopen here.
