### ISSUE TITLE
Allow configuring the location of the database

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope-frecency.nvim#22]
It'd be nice if we could specify the location (and name) of the database file in the telescope setup; something like

```lua
telescope.setup {
  extensions = {
    frecency = {
       frecency_location = '~/.local/share/nvim/telescope/frecency.sqlite3'
    }
  },
}
```

(Rationale: with https://github.com/nvim-telescope/telescope-smart-history.nvim, I might wish to move all my telescope files into one single directory.)

**Comment by sunjon** [comment]
It's been a while since I've looked at the code. It appears that there's an `opts.docs_root` (not the best name) parameter that it should respect. Let me know if that does what you want.

**Comment by clason** [comment]
No, that doesn't seem to do anything for me.

**Comment by clason** [comment]
Yep, works -- for others, the `db_root` is the _directory_ (so `vim.fn.stdpath('data') .. '/telescope'` in my case) not the _file_.
