### ISSUE TITLE
[BREAKING CHANGE]: move from telescope.path to plenary.path

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope-frecency.nvim#23]
Just now https://github.com/nvim-telescope/telescope.nvim/pull/473 got merged, which deprecated `telescope.path`. Extensions should now switch to `plenary.path` instead.

(The deprecated module `telescope.path` will be removed in a short while, so there's a time-critical aspect here.)

**Comment by Conni2461** [comment]
Will update it
