### ISSUE TITLE
Remove deprecated function `tbl_flatten`

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope-frecency.nvim#259]
In Nvim 0.10, `vim.tbl_flatten` was deprecated in favor of `vim.iter(...):flatten().totable()` (see `:checkhealth vim.deprecated` warning after using the plugin). You can either add a backward compatibility shim that checks for `vim.iter`, or just raise the minimum version to Nvim 0.10.

(On a related note, I'd suggest explicitly stating the minimum supported Neovim version in the Readme.)

**Comment by delphinus** [comment]
The upstream telscope's issue seems not to be processed. I start to think remove these deprecation warnings by bumping up this plugin's minimal requirements to v0.10.0.

**Comment by delphinus** [comment]
telescope.nvim still have not remove 0.9 support. In advance I will do it for telescope-frecency in #275.
