### ISSUE TITLE
[Feature request]: enhance the `workspaces` setting to use list of paths as values

### ISSUE THREAD

**Issue by gbcreation** [nvim-telescope/telescope-frecency.nvim#264]
Hi! Thank you for this very useful plugin.

Could it be possible to enhance it to specify a list of paths for the workspaces? The type of the `workspace` setting would be `table<string, string | table<string>>`. It would be similar to the `search_dirs` option of the Telescope `find_files` builtin and would be configured like this:

```lua
    workspaces = {
      ["conf"] = "/home/my_username/.config",
      ["data"] = { "/home/my_username/.local/share", "/usr/local/share" }
      ["project"] = "/home/my_username/projects",
      ["wiki"] = "/home/my_username/wiki",
    }
```

With this config, running `:Telescope frecency workspace=data` would display files from both `/home/my_username/.local/share` and `/usr/local/share` folders in the list.

**Comment by delphinus** [comment]
That's interesting. I will try to implement this.

**Comment by delphinus** [comment]
@gbcreation sorry for toooo late. I implemented this feature. Check it!
