### ISSUE TITLE
[Bug] Telescope mappings not working in frecency

### ISSUE THREAD

**Issue by gbcreation** [nvim-telescope/telescope-frecency.nvim#266]
Hi!

In my Telescope config, I set this mapping:

```lua
mappings = {
    i = {
        -- other mappings...
        ['<tab>'] = actions.move_selection_next,
        -- other mappings...
    }
}
```

But in Telescope frecency, the `Tab` key does not work. Is there something special to configure?

**Comment by delphinus** [comment]
Same as #48.

**Comment by gbcreation** [comment]
@delphinus thanks for notifying. Closing this isue then.

**Comment by delphinus** [comment]
Thanks. Now I know many users have trouble with this. I will take more precedence over other problems.

**Comment by delphinus** [comment]
@gbcreation #48 has been fixed in master. Check it!
