### ISSUE TITLE
packer example in README should specify requirement for sql.nvim

### ISSUE THREAD

**Issue by wbthomason** [nvim-telescope/telescope-frecency.nvim#27]
Just as a note: the `packer` plugin spec in the README probably ought to add a `requires = 'tami5/sql.nvim'` key, for people who just copy-paste that example and miss that `sql.nvim` is required.

**Comment by sunjon** [comment]
Thanks, I'll add that.
Telescope will soon have a `:checkhealth` that will also highlight the dependency.
