### ISSUE TITLE
Can't recognize upper case letters 

### ISSUE THREAD

**Issue by glyh** [nvim-telescope/telescope-frecency.nvim#36]
[![asciicast](https://asciinema.org/a/sQtzRV2eCVYAMe1zz4v6hDYUQ.svg)](https://asciinema.org/a/sQtzRV2eCVYAMe1zz4v6hDYUQ)

**Comment by vando026** [comment]
I also experience the same problem. 
![S1](https://user-images.githubusercontent.com/36604253/147142542-67636c92-4169-4369-b676-e0369d9949a9.png)
![S2](https://user-images.githubusercontent.com/36604253/147142556-717dc6d7-1112-4fe1-a057-f94b79ed1b1d.png)

**Comment by shaheenfawzy** [comment]
I don't know if the extension maintainer has higher priority issues to address, but fixing this would be much appreciated.
@delphinus

**Comment by delphinus** [comment]
The current logic uses telescope's `sorters.get_substr_matcher` itself that uses [always lower cases](https://github.com/nvim-telescope/telescope.nvim/blob/b744cf59752aaa01561afb4223006de26f3836fd/lua/telescope/sorters.lua#L539-L539) to match.

IMO to solve this, we must create frecency's original sorter and it should change its behavior by `'smartcase'` option. I'll try it.

**Comment by delphinus** [comment]
I implemented in trial: #36. If `'smartcase'` is on, it matches upper case letters when prompt string includes one upper case letter at least.

* prompt: `abc` → matches: `abc`, `ABC`, `aBc`
* prompt: `aBc` → matches: `aBc`

If `'smartcase'` is off, the behavior is not changed.

**Comment by shaheenfawzy** [comment]
thank you for the immediate response and hard work, can you tell me what to do to test it locally, do I fork the extension and merge the pr and download the fork locally and test it there's another way?

**Comment by shaheenfawzy** [comment]
I've downloaded the extension and loaded it locally checked out in the feat/smartcase branch and it's working out of the box flawlessly. can't wait for it to be merged in the main branch.

**Comment by delphinus** [comment]
Ah, `'smartcase'` is not an option for telescope-frecency. This is for Neovim itself: [Options - Neovim docs](https://neovim.io/doc/user/options.html#'smartcase').

```lua
-- in your init.lua
vim.opt.smartcase = true

-- and setup telescope
require("telescope").setup { ... }
```

Hmm, do you think which is understandable for users, frecency has its original `smartcase` option, or frecency respect `'smartcase'` option?

----

BTW, many plugin managers, such as lazy.nvim, supports `branch` option to specify plugin you want. You can test #177 with this setting.

```lua
require("lazy").setup {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = { { "nvim-telescope/telescope.nvim", branch = "feat/smartcase" } },
    config = function()
      ……
    end,
  },

  ……

  }
}
```

**Comment by shaheenfawzy** [comment]
I didn't know about the neovim smartcase option untill you told me about it, but I consider myself a beginner user so I think it would be more intuitive if it's used as frecency built-in option, or maybe better respect the neovim smartcase option unless stated otherwise in the extension options.
as for the branch option in lazy.nvim I didn't know about it, but I checked out the branch manually I'll will try it out and report back, thanks.

**Comment by shaheenfawzy** [comment]
I tried it out and set the branch in the lazy.nvim to feat/smartcase and set vim.opt.smartcase = true, but it didn't work as expected
![image](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/66196864/f66ea5cb-86eb-46a4-a474-630687f9fc46)
![image](https://github.com/nvim-telescope/telescope-frecency.nvim/assets/66196864/22721876-9080-4cc6-adc1-caa656e8aa87)

**Comment by delphinus** [comment]
I checked with this minimal init.lua and it works validly.

```lua
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      { "nvim-lua/plenary.nvim" },
      { "nvim-telescope/telescope-frecency.nvim", branch = "feat/smartcase" },
    },
    cmd = { "Telescope" },
    keys = { { "<leader>fr", "<cmd>Telescope frecency workspace=CWD<CR>" } },
    config = true,
  },
}

vim.opt.smartcase = true
```

[![asciicast](https://asciinema.org/a/642731.svg)](https://asciinema.org/a/642731)

I tested on Neovim v0.9.5 and HEAD. Can you show me your whole init.lua and Neovim version?

**Comment by shaheenfawzy** [comment]
I don't know what was wrong but when I changed the repo from the local one that I cloned to the one hosted on github it worked, thank you for your hard work can't wait for it to be merged in the master branch, I think this issue should be closed now.

**Comment by shaheenfawzy** [comment]
what have you decided on regarding enabling the smartcase option, using the global neovim smartcase option or the frecency extension option or a mix of both as I mentioned above?

**Comment by delphinus** [comment]
I think using Neovim's native option `'smartcase'` is better because the meaning is exactly the same as the purpose -- matching upper case letters only when input string includes one upper case at least. Another way, that is, adding `smartcase` to frecency is redundant in that sense.

OK, I will add note for this, and merge #177 later.

**Comment by delphinus** [comment]
The telescope's matcher now has the same feature as here. I have removed frecency's one and made it use telescope's one in #184.

**Comment by MaroonedMind** [comment]
Are there any other configuration requirements for the fix to work correctly? 
I'm using latest version of telescope-frecency, with both ignorecase and smartcase set to true, yet still have the old behavior where uppercase letters are not being recognized.

telescope.lua plugin config: 
```
-- import telescope plugin safely
local telescope_setup, telescope = pcall(require, "telescope")
if not telescope_setup then
  return
end

-- import telescope actions safely
local actions_setup, actions = pcall(require, "telescope.actions")
if not actions_setup then
  return
end

-- configure telescope
telescope.setup({
  extensions = {
    -- file_browser = {layout_strategy = "horizontal", sorting_strategy = "ascending"},
    heading = {treesitter = true},
    frecency = {
      default_workspace='CWD',
      show_scores = true,
      show_unindexed = false,
      ignore_patterns = {
        "*.git/*",
        "*/tmp/*"
      },
      workspaces = {
        ["conf"]    = "~/.config/nvim",
        ["code"]    = "~/Code"
      }
    },
    ["ui-select"] = {require("telescope.themes").get_dropdown({})}
  },
  defaults = {
    cache_picker = {num_pickers = 10},
    dynamic_preview_title = true,
    layout_strategy = "vertical",
    layout_config = {
      vertical = {
        width = 0.9, height = 0.9, preview_height = 0.6, preview_cutoff = 0
      }
    },
    path_display = {"smart", shorten = {len = 3}},
    wrap_results = true,
    mappings = {
      i = {
        ["<C-k>"] = actions.move_selection_previous, -- move to prev result
        ["<C-j>"] = actions.move_selection_next, -- move to next result
        ["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist, -- send selected to quickfixlist
      },
    },
  },
})

telescope.load_extension("fzf")
telescope.load_extension("ui-select")
telescope.load_extension("frecency")

vim.opt.smartcase = true
vim.opt.ignorecase = true
```

Telescope find files:
<img width="1559" alt="image" src="https://github.com/nvim-telescope/telescope-frecency.nvim/assets/54432203/9fb2dda2-439a-4b6b-a388-226da44a3fb1">

Telescope frecency:
<img width="1569" alt="image" src="https://github.com/nvim-telescope/telescope-frecency.nvim/assets/54432203/5a05ff40-e7a3-4ab6-809f-e84d7499a53d">

**Comment by delphinus** [comment]
I found the latest telescope's release does not include https://github.com/nvim-telescope/telescope.nvim/pull/2950. So I will revert this change until telescope will release it.

**Comment by delphinus** [comment]
@MaroonedMind Probably solved. Check it again.

**Comment by MaroonedMind** [comment]
Just checked, it's working properly now. Thank you!
