### ISSUE TITLE
Buffer filetype is `frecency` and not `TelescopePrompt`

### ISSUE THREAD

**Issue by euoia** [nvim-telescope/telescope-frecency.nvim#37]
Normally when opening the Telescope prompt the buffer filetype is `TelescopePrompt`. If you open a telescope-frecency, the buffer filetype is `frecency`. This is:
1. Somewhat unexpected and,
2. Bloats user configuration for handling of TelescopePrompt buffers, and
3. Might be the source of bugs for users trying to handle TelescopePrompt buffers.

For context, the reason I encountered this is because of this issue: https://github.com/nvim-telescope/telescope.nvim/issues/94#issuecomment-905314431

To reproduce:
1. Open Telescope or Frecency
2. Execute `:lua print(vim.bo.filetype)`

**Comment by adrian5** [comment]
I think this _might_ be resolved. My statusline updates to `TelescropePrompt` when I run (`:Telescope frecency`).

**Comment by delphinus** [comment]
This is fixed by #134. Thank you for your point.
