### ISSUE TITLE
Using as a sorter

### ISSUE THREAD

**Issue by chmln** [nvim-telescope/telescope-frecency.nvim#4]
First of all thank you for your work on this plugin. Prioritizing recently edited files is a simple yet such a great improvement over generic sorting. 

However I'd like to use this plugin for each project and have it be limited to a single workspace at a time. 

Maybe it's possible to extract the frecency-based db and sorter into a separate plugin?

**Comment by sunjon** [comment]
I have a change coming soon that I think will address everything you need :)
Stay tuned!

**Comment by sunjon** [comment]
I've merged a lot of changes related to workspaces. Give them a try and let me know what you think.

**Comment by sunjon** [comment]
I think this is able to be closed now.
If there's still anything from frecency that you'd like to be available in other finders, feel free to open an issue on the main telescope repo.
