### ISSUE TITLE
How to use  telescope-frecency as telescope search only on my cwd

### ISSUE THREAD

**Issue by ayoubelmhamdi** [nvim-telescope/telescope-frecency.nvim#41]
How to use `telescope.nvim` and [telescope-frecency.nvim](https://github.com/nvim-telescope/telescope-frecency.nvim) to search for each working directory only  
because `frecency.` search in the whole system `/ NOT cwd`
NOTE: cwd changed for each project or directory

**Comment by Conni2461** [comment]
Also see https://github.com/nvim-telescope/telescope-frecency.nvim/issues/14
and https://github.com/nvim-telescope/telescope-frecency.nvim/issues/16

**Comment by ayoubelmhamdi** [comment]
```
:Telescope frecency frecency default_text=:CWD
```
it's work but not perfect , i don't want to see `:CWD:` every time i open `:Telescope frecency frecency default_text=:CWD`
