### ISSUE TITLE
Telescope `path_display = { "truncate" }` default option is not applied

### ISSUE THREAD

**Issue by smjonas** [nvim-telescope/telescope-frecency.nvim#47]
I have set up Telescope like this:
```lua
telescope.setup {
    defaults = {
        path_display = { "truncate" }
    }
}
```
When using a builtin picker such as `find_files` this option is applied. However, when running the command `Telescope frecency` with this default option, the path is not truncated in the picker window. The same issue occurs when setting the option explicitly as in `Telescope frecency path_display="truncate"`.

Different options such as `Telescope frecency selection_caret="test"` are applied, however.

**Comment by Conni2461** [comment]
`path_display` is newer and nobody has moved to it yet. We got a PR a couple of days ago and i just merged it.

https://github.com/nvim-telescope/telescope-frecency.nvim/commit/4c46d468595d28d92bf340256e6cbbc3748ae6f0

Would be nice if you could test it and report back when it doesnt work (i havent tested it yet). I would close this issue for now but if it doesnt work feel free to reopen :)

**Comment by jonasstr** [comment]
Thank you, this fixed it!

**Comment by delphinus** [comment]
frecency has “workspace feature”, so that it tries to show paths truncated by cwd as the workspace. It ignores the default options for `path_display` in that process.

**Comment by aayestashn** [comment]
@delphinus Thanks for this amazing plugin is there any way to fix this issue ? Thanks again for your work

**Comment by delphinus** [comment]
@aayestashn sorry for late. This has been fixed. Now it respects `path_display` in `telescope.setup` or the command you typed. See #196 or README for the detail.

**Comment by aayestashn** [comment]
Thanks a lot @delphinus
