### ISSUE TITLE
[Enhancement] Add setting to confirm db cleanup automatically

### ISSUE THREAD

**Issue by foundObjects** [nvim-telescope/telescope-frecency.nvim#50]
I haven't ever said 'n' to the prompt to cleanup the frecency database, could we get a setup parameter to automatically say 'Y' there and skip the user prompt?

**Comment by FelipeLema** [comment]
I missed `db_safe_mode` too. It seems it addresses this... perhaps it could use better / more visible documentation?

**Comment by mawkler** [comment]
I really want this feature as well. I always press `y` as well, and I don't mind if it erases too much 🙂

**Comment by delphinus** [comment]
I am considering `db_safe_mode` option is useless in the current build. The default value of this is `true` and it means it does confirmation not only for `:FrecencyValidate` command but also in auto validating by `auto_validate` option (This is also `true` in default).

When you set `db_safe_mode` to `false`, it doesn't confirm anymore when `:FrecencyValidate!`, but it still does `:FrecencyValidate` and in auto validation. Isn't this needless? `db_safe_mode` should control confirmation for all situation, I think.

I'm planning to do breaking changes for this. If `db_safe_mode` is `true` (default value), it shows confirmation dialog. If `false`, it shows nothing.

How all do you think?

**Comment by fidelski** [comment]
I would be glad this would be implemented this way, I was already searching around, why the prompt appears even though I set `db_safe_mode` to false and `auto_validate` to true - there is also the problem for me that the prompt appears but it is not focused, so I need to enter `:FrecencyValidate` manually to focus the prompt to be able to type `y`.

**Comment by delphinus** [comment]
I did a breaking change as describe above. Now `db_safe_mode = false` makes it always no confirmation dialog for removing entries.
