### ISSUE TITLE
Is it possible to set CWD at call time?

### ISSUE THREAD

**Issue by danielo515** [nvim-telescope/telescope-frecency.nvim#55]
Hello, thank you very much for this plugin.
I was wondering if it is posssible to set the query at call time to CWD, or set the default_workspace.
This is what I tried:

```
Telescope frecency default_workspace='CWD'<cr>
```

But it does not work. Is it even possible?

**Comment by lucc** [comment]
You can try `Telescope frecency default_text=:CWD:`. 

Neither of these did work for me so maybe the handling of `default_workspace` is broken?
- `Telescope frecency default_workspace=CWD`
-  `Telescope frecency default_workspace=:CWD:`
- `lua require "telescope".extensions.frecency.frecency({default_workspace="CWD"})` 
- `lua require "telescope".extensions.frecency.frecency({default_workspace=":CWD:"})`
