### ISSUE TITLE
How to disable `Telescope-Frecency: removed n missing entries.` in messages?

### ISSUE THREAD

**Issue by kohane27** [nvim-telescope/telescope-frecency.nvim#59]
Hello there. Hope you're doing well.

Whenever `Telescope-Frecency` sees a changed file, it shows `Telescope-Frecency: removed 1 missing entries.` in the messages:

![screenshot-2022-05-29-12-10-56](https://user-images.githubusercontent.com/57322459/170851861-1a9cd6ef-9561-4e28-864c-22edcddce18c.png)

My current config:

```
frecency = {
      show_scores = false,
      show_unindexed = false,
      ignore_patterns = { "*.git/*", "*/tmp/*" },
      disable_devicons = false,
}
```

I looked into the doc and such `disable_removed_missing_entries_messages` option doesn't exist. Is it possible to disable such messages?

Any help is much appreciated. Thank you!

**Comment by kohane27** [comment]
A work-around is to modify `db_client.lua`:

1. `nvim ~/.local/share/nvim/site/pack/packer/start/telescope-frecency.nvim/lua/telescope/_extensions/frecency/db_client.lua`

2. Comment out `print(('Telescope-Frecency: removed %d missing entries.'):format(#pending_remove))`

**Comment by delphinus** [comment]
FYI: I pr-ed #75 to use `vim.notify` instead of `print()` to show such messages. You can see them in floating windows not to bother you with using [rcarriga/nvim-notify](https://github.com/rcarriga/nvim-notify).

**Comment by FelipeLema** [comment]
can wrap/re-define `vim.notify` to filter out this message [as shown here](https://github.com/rcarriga/nvim-notify/issues/114#issuecomment-1179754969)

**Comment by delphinus** [comment]
I changed the initialization process and that message appears when you call `:Telescope frecency` at the first time. I think it is less annoying.

If you want to remove that messages completely, try @FelipeLema's way above.
