### ISSUE TITLE
Error on recent commit

### ISSUE THREAD

**Issue by sahashirshendu** [nvim-telescope/telescope-frecency.nvim#70]
After updating to the latest [commit](https://github.com/nvim-telescope/telescope-frecency.nvim/commit/335cff15ea548d97e758fd2542479aff51868cb6) the following error shows up on nvim startup,
![2022-08-12_20-00](https://user-images.githubusercontent.com/87955430/184376592-854c3ad6-e363-405d-8558-5a4dee297b67.png)

```
System Info:
OS: Manjaro KDE 21.3.6
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

**Comment by Conni2461** [comment]
my bad, didn't realize that this event is not in the latest release. will revert, one sec

**Comment by Conni2461** [comment]
fixed in https://github.com/nvim-telescope/telescope-frecency.nvim/pull/71
