### ISSUE TITLE
Getting no results on Telescope frecency on Windows

### ISSUE THREAD

**Issue by sp1n0r** [nvim-telescope/telescope-frecency.nvim#8]
I'm on Windows 10 using NVIM v0.5.0-dev+1059-g55add1c1c.

I'm getting this when I do `:Telescope frecency`:
![1](https://user-images.githubusercontent.com/74260683/106790801-f2fa4380-664b-11eb-874e-6d0e69b22777.PNG)

`Telescope.log`:
``` 
[WARN  2/3/2021 6:02:25 PM] ...l\nvim\autoload\telescope.nvim\lua\telescope\pickers.lua:580: Failed with msg:  ...cal\nvim\autoload\telescope.nvim\lua\telescope\utils.lua:217: cannot resolve symbol 'linetabsize_col': Impossível localizar o procedimento especificado.
```
The last part translates to `Impossible to localize the specified procedure`

**Comment by sunjon** [comment]
Fixed in https://github.com/nvim-telescope/telescope-frecency.nvim/commit/3f6025c78a7ba19b93cd7969e76c2cf94ed72295
