### ISSUE TITLE
No highlight on the prompt now

### ISSUE THREAD

**Issue by delphinus** [nvim-telescope/telescope-frecency.nvim#83]
#81 is merged and it disables syntax highlight in the prompt because it had done `set filetype=frecency` for this purpose before this merge (See `syntax/frecency.vim`). We can do for this by methods below.

1. Do nothing. It does not highlight for now on.
   - It's unhappy for me ;(
2. Revert it and it uses `frecency` for the filetype also in the future.
3. Use newer API to set highlight for this.
   - We can set `nvim_buf_add_highlight` for this.
   - But this cannot colorize characters by regexp.
   - We should refresh it by `CursorMoved` events……?

It is understandable that the prompts should use `TelescopePrompt` because it is the telescope's way. Should we choose _3_ for this? How do you think?

**Comment by Conni2461** [comment]
Oh i am sorry, i missed this :( We can revert.

It sucks that i have to maintain this and have to little knowledge about the code base :/ But as a member, you should have rights, to merge and revert things ;)

**Comment by delphinus** [comment]
I've forgotten that I already have the auth! OK, I will revert and edit it.
