### ISSUE TITLE
`layout_config` and `layout_strategy` being ignored

### ISSUE THREAD

**Issue by chrisgrieser** [nvim-telescope/telescope-frecency.nvim#89]
probably similar to #88, it seems `layout_config` and `layout_strategy` are being ignored as well. However, as opposed to `path_display` in #88, they do inherit the default config – the issue is that you cannot change the frecency picker's config to anything else than the default config.

---

```lua
extensions = {
	frecency = {
		layout_strategy = "bottom_pane",
		layout_config = {
			horizontal = {
				width = 0.4,
			},
		},
	},
},
```

**Comment by delphinus** [comment]
Same as #88. Fixed.
