### ISSUE TITLE
Stale results

### ISSUE THREAD

**Issue by thenbe** [nvim-telescope/telescope-frecency.nvim#92]
First, thank you for this extremely useful plugin!

If `frecency` isn't your "main" picker, #90 could cause your db/results to become stale. How much so depends on your workflow.

For some workspaces, especially those with lots of files, I tend to use `find_files` picker the most. In those workspaces, the `frecency` db quickly becomes irrelevant because I haven't used the picker for the current session/task, which causes me to to depend on it less, resulting in a loop.

```mermaid
flowchart TD
    F(need to access recent file) -->A
    A(:Telescope frecency) -->B(Stale results)
    B --> C(use :Telescope oldfiles instead)
    C -->D(frecency db becomes more irrelevant)
    D -->F
```

As a workaround, I'm doing the following to initialize the db immediately:

```lua
config = function()
  require("telescope").load_extension("frecency")
  require("telescope._extensions.frecency.db_client").init()
end
```

**Comment by delphinus** [comment]
This does not happen in the current `master`. It inits the DB in `setup` (called from `telescope.load_extension`).
